In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df= pd.read_csv('covid_toy.csv')

In [4]:
df.sample(5)

    age  gender  fever   cough       city has_covid
16   69  Female  103.0    Mild    Kolkata       Yes
47   18  Female  104.0    Mild  Bangalore        No
32   34  Female  101.0  Strong      Delhi       Yes
58   23    Male   98.0  Strong     Mumbai       Yes
28   16    Male  104.0    Mild    Kolkata        No

In [5]:
df.isna().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
df['fever'].unique()

array([103., 100., 101.,  98.,  nan,  99., 102., 104.])

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
test_size=0.2)

In [8]:
X_train

    age  gender  fever   cough       city
88    5  Female  100.0    Mild    Kolkata
67   65    Male   99.0    Mild  Bangalore
10   75  Female    NaN    Mild      Delhi
2    42    Male  101.0    Mild      Delhi
4    65  Female  101.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
1    27    Male  100.0    Mild      Delhi
39   50  Female  103.0    Mild    Kolkata
72   83  Female  101.0    Mild    Kolkata
99   10  Female   98.0  Strong    Kolkata
37   55    Male  100.0    Mild    Kolkata

[80 rows x 5 columns]

# without Column Transformer

In [13]:
si = SimpleImputer()
x_train_fever= si.fit_transform(X_train[['fever']])

x_test_fever =si.fit_transform(X_train[['fever']])

In [17]:
x_train_fever.shape

(80, 1)

In [45]:
oe= OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])
X_test_cough = oe.fit_transform(X_test[['cough']])

In [23]:
oe.categories

[['Mild', 'Strong']]

In [36]:
ohe = OneHotEncoder(drop='first',sparse_output=False)

In [39]:
x_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

x_test_gender_city = ohe.fit_transform(X_test[['gender','city']])
x_train_gender_city.shape

(80, 4)

In [40]:
X_train_age = X_train.drop(columns = ['gender','fever','cough','city']).values
x_test_age = X_test.drop(columns=['gender','city','cough','city']).values

In [41]:
X_train_age.shape

(80, 1)

In [48]:
# X_train_transformed = np.concatenate((X_train_age,x_train_fever,x_train_gender_city,X_train_cough),axis=1)
# # also the test data
# X_test_transformed = np.concatenate((x_test_age,x_test_fever,x_test_gender_city,X_test_cough),axis=1)

# X_train_transformed.shape

In [50]:
from sklearn.compose import ColumnTransformer

In [53]:
Transformr = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output= False, drop='first'),['gender','city'])
],remainder='passthrough')

In [54]:
Transformr.fit_transform(X_train).shape

(80, 7)

In [56]:
Transformr.transform(X_test).shape

(20, 7)